### ISSUE TITLE
Functionality Checklist

### ISSUE THREAD

**Issue by dr-jts** [CrunchyData/pg_featureserv#1]
# `pg-featureserv` Functionality

### API
- [ ] landing page
- [ ] `api` - OpenAPI schema endpoint 
- [ ] `conformance` - OAF Conformance endpoint 
- [ ] `collections`
- [ ] `collections/id`
- [ ] `collections/id/items`
- [ ] `collections/id/items/id`

#### Feature parameters
- [ ] `bbox`
- [ ] attribute filtering
- [ ] paging

### User Interface (HTML)
- [ ] map display of feature collection
- [ ] map display of single feature

### Database
- [ ] layer column schema
- [ ] PostGIS 3.0 `AsGeoJSON` record
- [ ] PostGIS 2.x `AsGeoJSON` geometry with attribute encoding

### Development
- [ ] Unit tests
